/*
 * ======================================================
 * ⚠️ THIS FILE IS AUTO-GENERATED — DO NOT EDIT MANUALLY
 * ------------------------------------------------------
 * Generated by OpenAPI tooling
 *
 * Any changes made to this file will be overwritten.
 * ======================================================
 */

export interface paths {
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create user
     * @description Create a new user
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateUserBody'];
        };
      };
      responses: {
        /** @description User created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current user
     * @description Get current authenticated user
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update current user
     * @description Update current authenticated user
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateUserBody'];
        };
      };
      responses: {
        /** @description User updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    trace?: never;
  };
  '/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user
     * @description Get user by ID
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description User not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/messages/{conversationId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get messages
     * @description Get messages for a conversation
     */
    get: {
      parameters: {
        query?: {
          limit?: number;
          before?: number | null;
        };
        header?: never;
        path: {
          conversationId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of messages */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /**
     * Post message
     * @description Post a message to a conversation
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          conversationId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['PostMessageBody'];
        };
      };
      responses: {
        /** @description Message created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/messages/{conversationId}/{messageId}/read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Mark as read
     * @description Mark a message as read
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          conversationId: string;
          messageId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Message marked as read */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    trace?: never;
  };
  '/conversations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List conversations
     * @description Get all conversations for the current user
     */
    get: {
      parameters: {
        query?: {
          limit?: number;
          offset?: number | null;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of conversations */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /**
     * Create conversation
     * @description Create a new conversation
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateConversationBody'];
        };
      };
      responses: {
        /** @description Conversation created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/conversations/{conversationId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get conversation
     * @description Get a specific conversation by ID
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          conversationId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Conversation details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Conversation not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update conversation
     * @description Update conversation settings
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          conversationId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateConversationBody'];
        };
      };
      responses: {
        /** @description Conversation updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    trace?: never;
  };
  '/conversations/subscribe/{conversationId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Subscribe to conversation
     * @description Subscribe to conversation events (SSE)
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          conversationId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Event stream */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/conversations/{conversationId}/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add member
     * @description Add a member to a conversation
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          conversationId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['AddMemberBody'];
        };
      };
      responses: {
        /** @description Member added */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/conversations/{conversationId}/members/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove member
     * @description Remove a member from a conversation
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          conversationId: string;
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Member removed */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/conversations/{conversationId}/leave': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Leave conversation
     * @description Leave a conversation
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          conversationId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Left conversation */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateUserBody:
      | {
          /** @enum {string} */
          role: 'PATIENT';
          /** Format: email */
          email: string;
          firstName: string;
          lastName: string;
          phoneNumber: string;
          /** Format: date-time */
          dateOfBirth: string;
          /** @enum {string} */
          gender: 'MALE' | 'FEMALE' | 'OTHER' | 'PREFER_NOT_TO_SAY';
          emergencyContactName: string;
          emergencyContactPhone: string;
        }
      | {
          /** @enum {string} */
          role: 'DOCTOR';
          /** Format: email */
          email: string;
          firstName: string;
          lastName: string;
          phoneNumber: string;
          /** Format: date-time */
          dateOfBirth: string;
          /** @enum {string} */
          gender: 'MALE' | 'FEMALE' | 'OTHER' | 'PREFER_NOT_TO_SAY';
          /** @enum {string} */
          specialty:
            | 'FAMILY_MEDICINE'
            | 'INTERNAL_MEDICINE'
            | 'PEDIATRICS'
            | 'CARDIOLOGY'
            | 'DERMATOLOGY'
            | 'ENDOCRINOLOGY'
            | 'GASTROENTEROLOGY'
            | 'NEUROLOGY'
            | 'OBSTETRICS_GYNECOLOGY'
            | 'ONCOLOGY'
            | 'OPHTHALMOLOGY'
            | 'ORTHOPEDICS'
            | 'PSYCHIATRY'
            | 'RADIOLOGY'
            | 'SURGERY'
            | 'UROLOGY'
            | 'OTHER';
          licenseNumber: string;
          /** @enum {string} */
          province:
            | 'AB'
            | 'BC'
            | 'MB'
            | 'NB'
            | 'NL'
            | 'NS'
            | 'NT'
            | 'NU'
            | 'ON'
            | 'PE'
            | 'QC'
            | 'SK'
            | 'YT';
        };
    UpdateUserBody: {
      /** @enum {string} */
      role: 'PATIENT';
      /** Format: email */
      email?: string;
      phoneNumber?: string;
      /** @enum {string} */
      gender?: 'MALE' | 'FEMALE' | 'OTHER' | 'PREFER_NOT_TO_SAY';
      notificationsEnabled?: boolean;
      emergencyContactName?: string;
      emergencyContactPhone?: string;
    };
    PostMessageBody: {
      content: string;
      attachments?: string[];
    };
    CreateConversationBody: {
      userIds: string[];
      title?: string;
    };
    UpdateConversationBody: {
      title: string;
    };
    AddMemberBody: {
      /** Format: uuid */
      userId: string;
      /**
       * @default MEMBER
       * @enum {string}
       */
      role: 'MEMBER' | 'ADMIN';
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
