/*
 * ======================================================
 * ⚠️ THIS FILE IS AUTO-GENERATED — DO NOT EDIT MANUALLY
 * ------------------------------------------------------
 * Generated by OpenAPI tooling
 *
 * Any changes made to this file will be overwritten.
 * ======================================================
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const ConversationListItem = z
  .object({
    id: z.string(),
    title: z.string().nullable(),
    isGroup: z.boolean(),
    createdAt: z.string(),
  })
  .passthrough();
const CreateConversationBody = z
  .object({
    userIds: z.array(z.string().min(1)).min(1).max(50),
    title: z.string().min(1).max(100).optional(),
  })
  .passthrough();
const ConversationDetail = z
  .object({
    id: z.string(),
    title: z.string().nullable(),
    isGroup: z.boolean(),
    createdAt: z.string(),
    members: z.array(
      z
        .object({
          id: z.string(),
          userId: z.string(),
          role: z.string(),
          user: z
            .object({ firstName: z.string(), lastName: z.string() })
            .passthrough()
            .optional(),
        })
        .passthrough()
    ),
  })
  .passthrough();
const UpdateConversationBody = z
  .object({ title: z.string().min(1).max(100) })
  .passthrough();
const AddMemberBody = z
  .object({
    userId: z.string().min(1),
    role: z.enum(['MEMBER', 'ADMIN']).optional().default('MEMBER'),
  })
  .passthrough();
const PostMessageBody = z
  .object({
    content: z.string().min(1).max(10000),
    attachments: z.array(z.string()).max(10).optional(),
  })
  .passthrough();
const UserListItem = z
  .object({
    id: z.string(),
    firstName: z.string(),
    lastName: z.string(),
    email: z.string().email(),
    role: z.enum(['PATIENT', 'DOCTOR', 'ADMIN']),
  })
  .passthrough();
const CreateUserBody = z.union([
  z
    .object({
      role: z.literal('PATIENT'),
      email: z.string().email(),
      firstName: z.string().min(1).max(50),
      lastName: z.string().min(1).max(50),
      phoneNumber: z.string().min(10).max(15),
      dateOfBirth: z.string().datetime({ offset: true }),
      gender: z.enum(['MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY']),
      emergencyContactName: z.string().min(1).max(50),
      emergencyContactPhone: z.string().min(10).max(15),
    })
    .passthrough(),
  z
    .object({
      role: z.literal('DOCTOR'),
      email: z.string().email(),
      firstName: z.string().min(1).max(50),
      lastName: z.string().min(1).max(50),
      phoneNumber: z.string().min(10).max(15),
      dateOfBirth: z.string().datetime({ offset: true }),
      gender: z.enum(['MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY']),
      specialty: z.enum([
        'FAMILY_MEDICINE',
        'INTERNAL_MEDICINE',
        'PEDIATRICS',
        'CARDIOLOGY',
        'DERMATOLOGY',
        'ENDOCRINOLOGY',
        'GASTROENTEROLOGY',
        'NEUROLOGY',
        'OBSTETRICS_GYNECOLOGY',
        'ONCOLOGY',
        'OPHTHALMOLOGY',
        'ORTHOPEDICS',
        'PSYCHIATRY',
        'RADIOLOGY',
        'SURGERY',
        'UROLOGY',
        'OTHER',
      ]),
      licenseNumber: z.string().min(1).max(50),
      province: z.enum([
        'AB',
        'BC',
        'MB',
        'NB',
        'NL',
        'NS',
        'NT',
        'NU',
        'ON',
        'PE',
        'QC',
        'SK',
        'YT',
      ]),
    })
    .passthrough(),
]);
const UpdateUserBody = z
  .object({
    role: z.literal('PATIENT'),
    email: z.string().email().optional(),
    phoneNumber: z.string().min(10).max(15).optional(),
    gender: z.enum(['MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY']).optional(),
    notificationsEnabled: z.boolean().optional(),
    emergencyContactName: z.string().min(1).max(50).optional(),
    emergencyContactPhone: z.string().min(10).max(15).optional(),
  })
  .passthrough();

export const schemas = {
  ConversationListItem,
  CreateConversationBody,
  ConversationDetail,
  UpdateConversationBody,
  AddMemberBody,
  PostMessageBody,
  UserListItem,
  CreateUserBody,
  UpdateUserBody,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/conversations',
    alias: 'getConversations',
    description: `Get all conversations for the current user`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().gte(1).lte(100).optional().default(50),
      },
      {
        name: 'offset',
        type: 'Query',
        schema: z.number().gte(0).nullish().default(0),
      },
    ],
    response: z.array(ConversationListItem),
  },
  {
    method: 'post',
    path: '/conversations',
    alias: 'postConversations',
    description: `Create a new conversation`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: CreateConversationBody,
      },
    ],
    response: ConversationDetail,
  },
  {
    method: 'get',
    path: '/conversations/:conversationId',
    alias: 'getConversationsConversationId',
    description: `Get a specific conversation by ID`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'conversationId',
        type: 'Path',
        schema: z.string().uuid(),
      },
    ],
    response: z.void(),
    errors: [
      {
        status: 404,
        description: `Conversation not found`,
        schema: z.void(),
      },
    ],
  },
  {
    method: 'patch',
    path: '/conversations/:conversationId',
    alias: 'patchConversationsConversationId',
    description: `Update conversation settings`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: z.object({ title: z.string().min(1).max(100) }).passthrough(),
      },
      {
        name: 'conversationId',
        type: 'Path',
        schema: z.string().uuid(),
      },
    ],
    response: z.void(),
  },
  {
    method: 'delete',
    path: '/conversations/:conversationId/leave',
    alias: 'deleteConversationsConversationIdleave',
    description: `Leave a conversation`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'conversationId',
        type: 'Path',
        schema: z.string().uuid(),
      },
    ],
    response: z.void(),
  },
  {
    method: 'post',
    path: '/conversations/:conversationId/members',
    alias: 'postConversationsConversationIdmembers',
    description: `Add a member to a conversation`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: AddMemberBody,
      },
      {
        name: 'conversationId',
        type: 'Path',
        schema: z.string().uuid(),
      },
    ],
    response: z.void(),
  },
  {
    method: 'delete',
    path: '/conversations/:conversationId/members/:userId',
    alias: 'deleteConversationsConversationIdmembersUserId',
    description: `Remove a member from a conversation`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'conversationId',
        type: 'Path',
        schema: z.string().uuid(),
      },
      {
        name: 'userId',
        type: 'Path',
        schema: z.string().min(1),
      },
    ],
    response: z.void(),
  },
  {
    method: 'get',
    path: '/conversations/subscribe/:conversationId',
    alias: 'getConversationssubscribeConversationId',
    description: `Subscribe to conversation events (SSE)`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'conversationId',
        type: 'Path',
        schema: z.string().uuid(),
      },
    ],
    response: z.void(),
  },
  {
    method: 'get',
    path: '/messages/:conversationId',
    alias: 'getMessagesConversationId',
    description: `Get messages for a conversation`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'conversationId',
        type: 'Path',
        schema: z.string().uuid(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().gte(1).lte(100).optional().default(50),
      },
      {
        name: 'before',
        type: 'Query',
        schema: z.number().nullish(),
      },
    ],
    response: z.array(
      z
        .object({
          id: z.string(),
          conversationId: z.string(),
          senderId: z.string(),
          body: z.string(),
          isRead: z.boolean(),
          attachments: z.array(z.string()),
          createdAt: z.string(),
          updatedAt: z.string(),
          sender: z
            .object({
              firstName: z.string(),
              lastName: z.string(),
              role: z.string(),
            })
            .passthrough()
            .optional(),
        })
        .passthrough()
    ),
  },
  {
    method: 'post',
    path: '/messages/:conversationId',
    alias: 'postMessagesConversationId',
    description: `Post a message to a conversation`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: PostMessageBody,
      },
      {
        name: 'conversationId',
        type: 'Path',
        schema: z.string().uuid(),
      },
    ],
    response: z
      .object({
        id: z.string(),
        conversationId: z.string(),
        senderId: z.string(),
        body: z.string(),
        createdAt: z.string(),
      })
      .passthrough(),
  },
  {
    method: 'patch',
    path: '/messages/:conversationId/:messageId/read',
    alias: 'patchMessagesConversationIdMessageIdread',
    description: `Mark a message as read`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'conversationId',
        type: 'Path',
        schema: z.string().uuid(),
      },
      {
        name: 'messageId',
        type: 'Path',
        schema: z.string().uuid(),
      },
    ],
    response: z.void(),
  },
  {
    method: 'get',
    path: '/users',
    alias: 'getUsers',
    description: `List all users for chat selection`,
    requestFormat: 'json',
    response: z.array(UserListItem),
    errors: [
      {
        status: 401,
        description: `Unauthorized`,
        schema: z.void(),
      },
    ],
  },
  {
    method: 'post',
    path: '/users',
    alias: 'postUsers',
    description: `Create a new user`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: CreateUserBody,
      },
    ],
    response: z.void(),
    errors: [
      {
        status: 400,
        description: `Bad Request`,
        schema: z.void(),
      },
    ],
  },
  {
    method: 'get',
    path: '/users/:id',
    alias: 'getUsersId',
    description: `Get user by ID`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'id',
        type: 'Path',
        schema: z.string().min(1),
      },
    ],
    response: z.void(),
    errors: [
      {
        status: 404,
        description: `User not found`,
        schema: z.void(),
      },
    ],
  },
  {
    method: 'get',
    path: '/users/me',
    alias: 'getUsersme',
    description: `Get current authenticated user`,
    requestFormat: 'json',
    response: z.void(),
    errors: [
      {
        status: 401,
        description: `Unauthorized`,
        schema: z.void(),
      },
    ],
  },
  {
    method: 'patch',
    path: '/users/me',
    alias: 'patchUsersme',
    description: `Update current authenticated user`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: UpdateUserBody,
      },
    ],
    response: z.void(),
  },
]);

export const api = new Zodios(endpoints);

export function createApiClient(baseUrl: string, options?: ZodiosOptions) {
  return new Zodios(baseUrl, endpoints, options);
}
